source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'TableViewConfigurator_Example' do
  pod 'TableViewConfigurator', :path => '../'
  
  target 'TableViewConfigurator_Tests' do
      inherit! :search_paths
      pod 'Quick', '~> 1.3'
      pod 'Nimble', '~> 7.3'
  end
end
