source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'TableViewConfigurator_Example' do
  pod 'TableViewConfigurator', :path => '../'
  
  target 'TableViewConfigurator_Tests' do
      inherit! :search_paths
      pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
      pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :branch => 'swift-3.0'
  end
end
