source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'TableViewConfigurator_Example' do
  pod 'TableViewConfigurator', :path => '../'
  
  target 'TableViewConfigurator_Tests' do
      inherit! :search_paths
      pod 'Quick', '~> 1.0'
      pod 'Nimble', '~> 5.1'
  end
end
